### ISSUE TITLE
python bug

### ISSUE THREAD

**Issue by pr4deepr** [labsyspharm/minerva_analysis#128]
Hi
   After following installation instructions for minerva_analysis using conda on a Windows 10 machine, I get the following bug:

```
Traceback (most recent call last):
  File "C:\Users\rajasekhar.p\minerva_analysis\run.py", line 5, in <module>
    from minerva_analysis import app
  File "C:\Users\rajasekhar.p\minerva_analysis\minerva_analysis\__init__.py", line 1, in <module>
    from flask import Flask
  File "C:\Users\rajasekhar.p\.conda\envs\minerva_analysis2\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\rajasekhar.p\.conda\envs\minerva_analysis2\lib\site-packages\jinja2\__init__.py)
```

I get this for extensions: gating and lensing..

BTW, these are some really cool tools you've created!

looking forward to playing with them.

Cheers
Pradeep

**Comment by nchuynh** [comment]
Hi Pradeep, thanks for checking out our tools!

Did you create your conda environment using the requirements.yml file from the Master branch? If yes, you'll just need to re-create your environment using the requirements from the specific branch you want to use (i.e. Visinity, Gater).

I believe this error is caused by an older version of Flask that's specified for the Master branch. Also the branches have deviated a bit from each other as we developed them and it's important to create specific environments for using each one. We're working on eventually harmonizing them.

**Comment by nchuynh** [comment]
Hi Pradeep, sorry for the delayed response. I chatted with the people that developed the lensing branch and they said that for the lensing tool, you should clone this repo: https://github.com/labsyspharm/scope2screen

The requirements yml file there should work for that tool.

**Comment by pr4deepr** [comment]
Thanks, is this in the README files? I couldn't find any info.

Cheers
Pradeep

**Comment by nchuynh** [comment]
It isn't in the README file. Scope2screen (i.e. the lensing tool) was published in IEEE and the developers created a separate repo for it. Visinity was also published and the repo is here: https://github.com/labsyspharm/visinity
