### ISSUE TITLE
Question regarding FIXME on gating branch

### ISSUE THREAD

**Issue by thejohnhoffer** [labsyspharm/minerva_analysis#93]
### Problem

When I try to activate the centroid rendering (OR-mode / pie-chart), I see an error [on this line](https://github.com/labsyspharm/minerva_analysis/blob/b44fe4f82f266cb97ea2a05105dcf8c6d9746cfd/minerva_analysis/client/src/js/views/csvGatingOverlay.js#L224):

```
CsvGatingOverlay.js:230 Uncaught TypeError: Cannot read properties of undefined (reading 'color')
    at eval (CsvGatingOverlay.js:230:113)
    at Array.forEach (<anonymous>)
    at eval (CsvGatingOverlay.js:224:36)
```

Here's what I can figure out:
- There's an object mapping called `_this.channel_list.currentChannels`.
- In that mapping, there are no keys that match the `gatingChannelIndices[i].index` that I have selected

It seems like the simplest fix would be to add the following conditional check:

```js
if (gatingChannelIndices[i].index in  _this.channel_list.currentChannels) {
 /* then draw the arcs */
}
```

## Replication

- I have loaded the `crop-crc01` dataset channel ome-tiff, mask tiff, quantification csv, and cluster csv
- I have selected one channel (`Hoechst0`) and one mask (`Keratin_570`)
- I click the Centroids (OR-mode) checkbox

## Question

However, I'm not sure if there's a logical error.  My question would be:
Should `_this.channel_list.currentChannels` contain all active channels?

I wonder if it is related to this FIXME statement:
```
Retrieve color (FIXME - need to integrate into viewer manager)
```

**Comment by thejohnhoffer** [comment]
It seems that `_this.channel_list.currentChannels` contains only the fluorescence channels, while `gatingChannelIndices` contains only the segmentation mask clusters.

**Comment by thejohnhoffer** [comment]
Ah, my issue stems from attempting to perform gating on a channel that is not selected.

So I've selected "Keratin" for gating on the right, but I didn't view that channel on the left.

It seems the software assumes that I'll only be gating against visible channels!
That may be a fine assumption, but perhaps an error message would be nice.
